dist: xenial
language: node_js
node_js:
    - node
install:
    - npm install
script:
    - npm run build
deploy:
    provider: s3
    bucket: "coa-ui"
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    local_dir: build
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    on:
        branch: master